services:
  llamafactory:
    image: hiyouga/llamafactory:0.9.3
    container_name: llamafactory
    ports:
      - "15555:7860"
      - "15556:8000"
    ipc: host
    tty: true
    # shm_size: "16gb"  # ipc: host is set
    stdin_open: true
    command: llamafactory-cli webui
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['2', '3']
            capabilities: [ gpu ]
    restart: unless-stopped
